// Generated by gencpp from file motion_planning/AV.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_MESSAGE_AV_H
#define MOTION_PLANNING_MESSAGE_AV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motion_planning
{
template <class ContainerAllocator>
struct AV_
{
  typedef AV_<ContainerAllocator> Type;

  AV_()
    : header()
    , laneID(0)
    , speed(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , acc(0.0)
    , heading(0.0)  {
    }
  AV_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , laneID(0)
    , speed(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , acc(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _laneID_type;
  _laneID_type laneID;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _acc_type;
  _acc_type acc;

   typedef float _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::motion_planning::AV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_planning::AV_<ContainerAllocator> const> ConstPtr;

}; // struct AV_

typedef ::motion_planning::AV_<std::allocator<void> > AV;

typedef boost::shared_ptr< ::motion_planning::AV > AVPtr;
typedef boost::shared_ptr< ::motion_planning::AV const> AVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_planning::AV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_planning::AV_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_planning::AV_<ContainerAllocator1> & lhs, const ::motion_planning::AV_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.laneID == rhs.laneID &&
    lhs.speed == rhs.speed &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.acc == rhs.acc &&
    lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_planning::AV_<ContainerAllocator1> & lhs, const ::motion_planning::AV_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::AV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::AV_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::AV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::AV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::AV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::AV_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_planning::AV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcc44aec6d849a4b2e718a007466ed54";
  }

  static const char* value(const ::motion_planning::AV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcc44aec6d849a4bULL;
  static const uint64_t static_value2 = 0x2e718a007466ed54ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_planning::AV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_planning/AV";
  }

  static const char* value(const ::motion_planning::AV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_planning::AV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 laneID\n"
"float32 speed\n"
"float32 latitude\n"
"float32 longitude\n"
"float32 acc\n"
"float32 heading\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::motion_planning::AV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_planning::AV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.laneID);
      stream.next(m.speed);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.acc);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_planning::AV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_planning::AV_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "laneID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.laneID);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLANNING_MESSAGE_AV_H
