// Generated by gencpp from file motion_planning/Cars.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_MESSAGE_CARS_H
#define MOTION_PLANNING_MESSAGE_CARS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motion_planning
{
template <class ContainerAllocator>
struct Cars_
{
  typedef Cars_<ContainerAllocator> Type;

  Cars_()
    : header()
    , objectID(0)
    , laneID(0)
    , objectType()
    , dx(0.0)
    , dy(0.0)
    , speed(0.0)
    , acc(0.0)
    , distanceFromAV(0.0)  {
    }
  Cars_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objectID(0)
    , laneID(0)
    , objectType(_alloc)
    , dx(0.0)
    , dy(0.0)
    , speed(0.0)
    , acc(0.0)
    , distanceFromAV(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _objectID_type;
  _objectID_type objectID;

   typedef int8_t _laneID_type;
  _laneID_type laneID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _objectType_type;
  _objectType_type objectType;

   typedef float _dx_type;
  _dx_type dx;

   typedef float _dy_type;
  _dy_type dy;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _acc_type;
  _acc_type acc;

   typedef float _distanceFromAV_type;
  _distanceFromAV_type distanceFromAV;





  typedef boost::shared_ptr< ::motion_planning::Cars_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_planning::Cars_<ContainerAllocator> const> ConstPtr;

}; // struct Cars_

typedef ::motion_planning::Cars_<std::allocator<void> > Cars;

typedef boost::shared_ptr< ::motion_planning::Cars > CarsPtr;
typedef boost::shared_ptr< ::motion_planning::Cars const> CarsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_planning::Cars_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_planning::Cars_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_planning::Cars_<ContainerAllocator1> & lhs, const ::motion_planning::Cars_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objectID == rhs.objectID &&
    lhs.laneID == rhs.laneID &&
    lhs.objectType == rhs.objectType &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.speed == rhs.speed &&
    lhs.acc == rhs.acc &&
    lhs.distanceFromAV == rhs.distanceFromAV;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_planning::Cars_<ContainerAllocator1> & lhs, const ::motion_planning::Cars_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::Cars_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::Cars_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::Cars_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::Cars_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::Cars_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::Cars_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_planning::Cars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4141725f390ac8dd13a07016926593a5";
  }

  static const char* value(const ::motion_planning::Cars_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4141725f390ac8ddULL;
  static const uint64_t static_value2 = 0x13a07016926593a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_planning::Cars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_planning/Cars";
  }

  static const char* value(const ::motion_planning::Cars_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_planning::Cars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 objectID \n"
"int8 laneID\n"
"string objectType\n"
"float32 dx\n"
"float32 dy\n"
"float32 speed\n"
"float32 acc\n"
"float32 distanceFromAV\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::motion_planning::Cars_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_planning::Cars_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objectID);
      stream.next(m.laneID);
      stream.next(m.objectType);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.speed);
      stream.next(m.acc);
      stream.next(m.distanceFromAV);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cars_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_planning::Cars_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_planning::Cars_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objectID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.objectID);
    s << indent << "laneID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.laneID);
    s << indent << "objectType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objectType);
    s << indent << "dx: ";
    Printer<float>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<float>::stream(s, indent + "  ", v.dy);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
    s << indent << "distanceFromAV: ";
    Printer<float>::stream(s, indent + "  ", v.distanceFromAV);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLANNING_MESSAGE_CARS_H
