// Generated by gencpp from file motion_planning/Cars_vector.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_MESSAGE_CARS_VECTOR_H
#define MOTION_PLANNING_MESSAGE_CARS_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <motion_planning/Cars.h>

namespace motion_planning
{
template <class ContainerAllocator>
struct Cars_vector_
{
  typedef Cars_vector_<ContainerAllocator> Type;

  Cars_vector_()
    : header()
    , cars()  {
    }
  Cars_vector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cars(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::motion_planning::Cars_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::motion_planning::Cars_<ContainerAllocator> >::other >  _cars_type;
  _cars_type cars;





  typedef boost::shared_ptr< ::motion_planning::Cars_vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_planning::Cars_vector_<ContainerAllocator> const> ConstPtr;

}; // struct Cars_vector_

typedef ::motion_planning::Cars_vector_<std::allocator<void> > Cars_vector;

typedef boost::shared_ptr< ::motion_planning::Cars_vector > Cars_vectorPtr;
typedef boost::shared_ptr< ::motion_planning::Cars_vector const> Cars_vectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_planning::Cars_vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_planning::Cars_vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_planning::Cars_vector_<ContainerAllocator1> & lhs, const ::motion_planning::Cars_vector_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cars == rhs.cars;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_planning::Cars_vector_<ContainerAllocator1> & lhs, const ::motion_planning::Cars_vector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::Cars_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::Cars_vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::Cars_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::Cars_vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::Cars_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::Cars_vector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_planning::Cars_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1f8459a9d28dbba0869e7fd9fb500bc";
  }

  static const char* value(const ::motion_planning::Cars_vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1f8459a9d28dbbaULL;
  static const uint64_t static_value2 = 0x0869e7fd9fb500bcULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_planning::Cars_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_planning/Cars_vector";
  }

  static const char* value(const ::motion_planning::Cars_vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_planning::Cars_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Cars[] cars\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: motion_planning/Cars\n"
"Header header\n"
"int8 objectID \n"
"int8 laneID\n"
"string objectType\n"
"float32 dx\n"
"float32 dy\n"
"float32 speed\n"
"float32 acc\n"
"float32 distanceFromAV\n"
;
  }

  static const char* value(const ::motion_planning::Cars_vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_planning::Cars_vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cars);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cars_vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_planning::Cars_vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_planning::Cars_vector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cars[]" << std::endl;
    for (size_t i = 0; i < v.cars.size(); ++i)
    {
      s << indent << "  cars[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::motion_planning::Cars_<ContainerAllocator> >::stream(s, indent + "    ", v.cars[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLANNING_MESSAGE_CARS_VECTOR_H
